/* Submodule for the transmission of the UART data frames*/
`define IDLE_STATE      3'b000
`define START_STATE     3'b001
`define TRANS_STATE     3'b010
`define PARITY_STATE    3'b011
`define STOP_STATE      3'b100
/*
* Module: uart_tx
* Transmits with even parity
*/
module uart_tx(
    input tick,                 // generated by buad_tick module
    input trigger,              // triggers transmission of data
    input reset,
    input wire[7:0] tx_data,    // the data to send
    output reg tx_line = 1'b1,         // transmission line out
    output reg busy = 1'b0             // indicates busyness of transmitter
);
// Internal signals
reg [2:0] tx_state = 1'b0; // for the transmission fsm
reg [2:0] tx_index = 1'b0; // the index of the bit being transmitted
reg [3:0] tx_acc = 1'b0; //accumulates oversampled ticks
reg tx_parity_bit; 

always @(posedge tick) begin
    if(!reset) begin
        tx_state <= `IDLE_STATE;
        tx_index <= 3'b0;
        tx_acc <= 4'b0;
        tx_line <= 1'b1; // idle is high
    end else begin
    if(tx_acc == 4'b1111)begin
      tx_acc <= 1'b0; // reset baud tick count    
        case(tx_state)

        `IDLE_STATE:begin
            tx_line <= 1'b1; // UART is high in idle state
            busy <= 1'b0;

            if(trigger == 1'b1 )begin
                busy <= 1'b1;
                tx_state <= `START_STATE;
            end

        end

        `START_STATE:begin
            tx_parity_bit <= 1'b0;
            busy <= 1'b1;
            tx_line <= 1'b0; // the start bit
            tx_index <= 3'b000;  // move index to start
            tx_state <= `TRANS_STATE;
        end

        `TRANS_STATE:begin
            busy <= 1'b1;
            tx_line <= tx_data[tx_index];
            tx_index <= tx_index + 1'b1;
            tx_parity_bit <= tx_data[tx_index] == 1'b1 ? ~tx_parity_bit : tx_parity_bit;
            tx_state <= (tx_index == 3'b111) ? `PARITY_STATE : `TRANS_STATE ;

        end

        `PARITY_STATE: begin
            busy <= 1'b1;
            tx_line <= tx_parity_bit;
            tx_state <= `STOP_STATE;
        end

        `STOP_STATE:begin
            busy <= 1'b1;
            tx_line <= 1'b1;
            tx_state <= `IDLE_STATE;
        end
        endcase
      end else begin
     tx_acc <= tx_acc + 1;
  end
    end 
end

endmodule
