; By: Joshua Bode
; An ecall "extension pack" included with Vuk's ecall_handler.s

system_time_area equ 0x0001_0710;
lower equ 0x0;
upper equ 0x4;

fix_parser_interrupt equ 0x1;

parser_area equ 0x0002_0080;

parser_info equ 0xC;

lfsr_area equ 0x0002_0180;

toggle_lfsr_data equ 0x8;
trade_data equ 0x0;
price_data equ 0x4;
lfsr_data_in equ 0x8;
lfsr_control equ 0xC;
ticker_id_mask equ 0b0111;

ecall_9
    j set_lfsr_seed

ecall_10
    j get_lfsr_params

ecall_11
    j get_system_time


; Sets the seed to the FIX_LFSR device
; args:
;       a0: The seed to set
;
; returns:
;       none
;

set_lfsr_seed
        li t0, lfsr_area;
        sw a0, lfsr_data_in[t0];
        sw zero, lfsr_control[t0]; send the seed
        ret

; Reads parameters generated by the FIX_LFSR device
; args:
;       none
;
; returns:
;       a0: (boolean) buy/sell side
;       a1: ticker id
;       a2: quantity
;       a3: price
;

get_lfsr_params
        li t0, lfsr_area;
        li t1, toggle_lfsr_data;
        sw t1, lfsr_control[t0]; pause the LFSR's operation
        nop;
        lw t1, trade_data[t0];
        sltz a0, t1; the side of the order is the MSB from the trade data addr.
        andi a1, t1, ticker_id_mask;
        slli a2, t1, 1; Left shift to remove the MSB
        srli a2, a2, 4; Right shift of 1 (offset from MSB) + 3 (ticker_id)
        lw a3, price_data[t0];
        nop;
        li t1, toggle_lfsr_data;
        sw t1, lfsr_control[t0]; resume the LFSR's operation
        ret

; Gets the RISC-V system time
;
; args:
;       none
;
; returns:
;       a0: lower bits
;       a1: higher bits
;

get_system_time
        li t0, system_time_area;
        lw a0, lower[t0] ;
        lw a1, upper[t1] ;
        ret